import {
  TrendingUp,
  Handshake,
  Receipt,
  Calculator,
  CreditCard,
  Package,
  FolderKanban,
  Users,
  Mail,
  BookUser,
  Waves,
  Settings,
  CalendarDays,
  type LucideIcon,
} from "lucide-react";

export const moduleIcons: Record<string, LucideIcon> = {
  ventas: TrendingUp,
  crm: Handshake,
  facturacion: Receipt,
  contabilidad: Calculator,
  gastos: CreditCard,
  inventario: Package,
  proyectos: FolderKanban,
  empleados: Users,
  correo: Mail,
  contacto: BookUser,
  piscina: Waves,
  configuraciones: Settings,
  calendario: CalendarDays,
};
