ALTER TABLE contactos
ADD COLUMN codigo VARCHAR(50),
ADD COLUMN nombre_fiscal VARCHAR(255),
ADD COLUMN fax VARCHAR(50),
ADD COLUMN movil VARCHAR(50),
ADD COLUMN persona_contacto VARCHAR(255),
ADD COLUMN nif VARCHAR(50),
ADD COLUMN agente VARCHAR(255),
ADD COLUMN tipo_cliente VARCHAR(50);
